name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu

    steps:
      - uses: actions/checkout@v4  # Mise à jour vers la v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Cache Buildozer global directory
        uses: actions/cache@v4  # Mise à jour vers la v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v4  # Mise à jour vers la v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Mise à jour vers la v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
